# Generated by Django 5.0.6 on 2024-06-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Password',
            new_name='password',
        ),
    ]
