# Generated by Django 5.0.6 on 2024-06-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_email_student_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
