# Generated by Django 5.0.6 on 2024-06-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_student_otp_remove_student_timestamp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18, max_length=2),
        ),
    ]
